image: registry.gitlap.ir/docker/hub/node

before_script:
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - cp .env.example .env.local 
    - yarn build
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
      - public
  only:
    - develope
